// Generated by herkos v0.1.1
// Wasm binary version: 1
// DO NOT EDIT

use herkos_runtime::*;

const MAX_PAGES: usize = 2;

pub trait ModuleHostTrait {
}

impl ModuleHostTrait for herkos_runtime::NoHost {}

pub struct Globals {
}

#[allow(dead_code)]
struct Env<'a, H: ModuleHostTrait + ?Sized> {
    pub host: &'a mut H,
    pub globals: &'a mut Globals,
}

pub const G0: i32 = 1024i32;
pub const G1: i32 = 58368i32;
pub const G2: i32 = 58368i32;
pub const G3: i32 = 123904i32;
pub const G4: i32 = 1024i32;
pub const G5: i32 = 123904i32;
pub const G6: i32 = 131072i32;
pub const G7: i32 = 0i32;
pub const G8: i32 = 1i32;

pub struct WasmModule(pub Module<Globals, MAX_PAGES, 0>);

pub fn new() -> WasmResult<WasmModule> {
    let mut __slot = core::mem::MaybeUninit::<Module<Globals, MAX_PAGES, 0>>::uninit();
    Module::try_init(&mut __slot, 2, Globals {}, Table::try_new(0)?).map_err(|_| WasmTrap::OutOfBounds)?;
    let module = unsafe { __slot.assume_init() };
    Ok(WasmModule(module))
}

#[allow(unused_mut, unused_variables, unused_assignments, clippy::only_used_in_recursion, clippy::needless_return, clippy::manual_range_contains, clippy::never_loop)]
fn func_0<H: ModuleHostTrait>(env: &mut Env<'_, H>, memory: &mut IsolatedMemory<MAX_PAGES>) -> WasmResult<()> {
    #[derive(Clone, Copy)]
    #[allow(dead_code)]
    enum Block { B0 }
    let mut __current_block = Block::B0;
    loop {
        match __current_block {
            Block::B0 => {
                return Ok(());
            }
        }
    }
}

#[allow(unused_mut, unused_variables, unused_assignments, clippy::only_used_in_recursion, clippy::needless_return, clippy::manual_range_contains, clippy::never_loop)]
fn func_1<H: ModuleHostTrait>(mut v0: i32, env: &mut Env<'_, H>, memory: &mut IsolatedMemory<MAX_PAGES>) -> WasmResult<()> {
    let mut v1: f32 = 0.0f32;
    let mut v2: f32 = 0.0f32;
    let mut v3: f32 = 0.0f32;
    let mut v4: i32 = 0i32;
    let mut v5: i32 = 0i32;
    let mut v6: i32 = 0i32;
    let mut v7: i32 = 0i32;
    let mut v8: f32 = 0.0f32;
    let mut v9: f32 = 0.0f32;
    let mut v10: i32 = 0i32;
    let mut v11: i32 = 0i32;
    let mut v12: i32 = 0i32;
    let mut v13: f32 = 0.0f32;
    let mut v14: f32 = 0.0f32;
    let mut v15: f32 = 0.0f32;
    let mut v16: i32 = 0i32;
    let mut v17: i32 = 0i32;
    let mut v18: i32 = 0i32;
    let mut v19: i32 = 0i32;
    let mut v20: i32 = 0i32;
    let mut v21: i32 = 0i32;
    let mut v22: i32 = 0i32;
    let mut v23: f32 = 0.0f32;
    let mut v24: f32 = 0.0f32;
    let mut v25: f32 = 0.0f32;
    let mut v26: f32 = 0.0f32;
    let mut v27: f32 = 0.0f32;
    let mut v28: f32 = 0.0f32;
    let mut v29: f32 = 0.0f32;
    let mut v30: f32 = 0.0f32;
    let mut v31: i32 = 0i32;
    let mut v32: i32 = 0i32;
    let mut v33: i32 = 0i32;
    let mut v34: f32 = 0.0f32;
    let mut v35: f32 = 0.0f32;
    let mut v36: f32 = 0.0f32;
    let mut v37: f32 = 0.0f32;
    let mut v38: f32 = 0.0f32;
    let mut v39: f32 = 0.0f32;
    let mut v40: f32 = 0.0f32;
    let mut v41: f32 = 0.0f32;
    let mut v42: i32 = 0i32;
    let mut v43: i32 = 0i32;
    let mut v44: i32 = 0i32;
    let mut v45: i32 = 0i32;
    let mut v46: f32 = 0.0f32;
    let mut v47: f32 = 0.0f32;
    #[derive(Clone, Copy)]
    #[allow(dead_code)]
    enum Block { B0, B1, B2, B3, B4, B5, B6 }
    let mut __current_block = Block::B0;
    loop {
        match __current_block {
            Block::B0 => {
                v4 = 41984i32;
                v5 = 1065353216i32;
                memory.store_i32(v4 as usize, v5)?;
                v6 = 50176i32;
                v7 = 0i32;
                memory.store_i32(v6 as usize, v7)?;
                v8 = 1f32;
                v9 = v8;
                v10 = 4i32;
                v11 = v10;
                v12 = v11;
                v13 = v9;
                v14 = v2;
                v15 = v3;
                __current_block = Block::B1;
                continue;
            }
            Block::B1 => {
                v16 = v12;
                v17 = 8192i32;
                v18 = if v16 == v17 { 1i32 } else { 0i32 };
                v19 = if v18 == 0 { 1 } else { 0 };
                if v19 != 0 {
                    __current_block = Block::B2;
                } else {
                    __current_block = Block::B4;
                }
                continue;
            }
            Block::B2 => {
                v20 = v12;
                v21 = 50176i32;
                v22 = v20.wrapping_add(v21);
                v23 = v14;
                v24 = 0.9999988f32;
                v25 = v23 * v24;
                v26 = v13;
                v27 = -0.0015339802f32;
                v28 = v26 * v27;
                v29 = v25 + v28;
                v30 = v29;
                memory.store_f32(v22 as usize, v29)?;
                v31 = v12;
                v32 = 41984i32;
                v33 = v31.wrapping_add(v32);
                v34 = v13;
                v35 = 0.9999988f32;
                v36 = v34 * v35;
                v37 = v14;
                v38 = 0.0015339802f32;
                v39 = v37 * v38;
                v40 = v36 + v39;
                v41 = v40;
                memory.store_f32(v33 as usize, v40)?;
                v42 = v12;
                v43 = 4i32;
                v44 = v42.wrapping_add(v43);
                v45 = v44;
                v46 = v30;
                v47 = v46;
                v12 = v45;
                v13 = v41;
                v14 = v47;
                v15 = v30;
                __current_block = Block::B1;
                continue;
            }
            Block::B3 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B4 => {
                __current_block = Block::B5;
                continue;
            }
            Block::B5 => {
                __current_block = Block::B6;
                continue;
            }
            Block::B6 => {
                return Ok(());
            }
        }
    }
}

#[allow(unused_mut, unused_variables, unused_assignments, clippy::only_used_in_recursion, clippy::needless_return, clippy::manual_range_contains, clippy::never_loop)]
fn func_2<H: ModuleHostTrait>(env: &mut Env<'_, H>, memory: &mut IsolatedMemory<MAX_PAGES>) -> WasmResult<i32> {
    let mut v1: i32 = 0i32;
    #[derive(Clone, Copy)]
    #[allow(dead_code)]
    enum Block { B0 }
    let mut __current_block = Block::B0;
    loop {
        match __current_block {
            Block::B0 => {
                v1 = 1024i32;
                return Ok(v1);
            }
        }
    }
}

#[allow(unused_mut, unused_variables, unused_assignments, clippy::only_used_in_recursion, clippy::needless_return, clippy::manual_range_contains, clippy::never_loop)]
fn func_3<H: ModuleHostTrait>(mut v0: i32, env: &mut Env<'_, H>, memory: &mut IsolatedMemory<MAX_PAGES>) -> WasmResult<()> {
    let mut v1: i32 = 0i32;
    let mut v2: i32 = 0i32;
    let mut v3: i32 = 0i32;
    let mut v4: i32 = 0i32;
    let mut v5: i32 = 0i32;
    let mut v6: i32 = 0i32;
    let mut v7: i32 = 0i32;
    let mut v8: i32 = 0i32;
    let mut v9: i32 = 0i32;
    let mut v10: i32 = 0i32;
    let mut v11: i32 = 0i32;
    let mut v12: f32 = 0.0f32;
    let mut v13: f32 = 0.0f32;
    let mut v14: f32 = 0.0f32;
    let mut v15: f32 = 0.0f32;
    let mut v16: f32 = 0.0f32;
    let mut v17: f32 = 0.0f32;
    let mut v18: f32 = 0.0f32;
    let mut v19: i32 = 0i32;
    let mut v20: i32 = 0i32;
    let mut v21: i32 = 0i32;
    let mut v22: i32 = 0i32;
    let mut v23: i32 = 0i32;
    let mut v24: i32 = 0i32;
    let mut v25: i32 = 0i32;
    let mut v26: i32 = 0i32;
    let mut v27: i32 = 0i32;
    let mut v28: i32 = 0i32;
    let mut v29: i32 = 0i32;
    let mut v30: i32 = 0i32;
    let mut v31: f32 = 0.0f32;
    let mut v32: f32 = 0.0f32;
    let mut v33: f32 = 0.0f32;
    let mut v34: f32 = 0.0f32;
    let mut v35: f32 = 0.0f32;
    let mut v36: f32 = 0.0f32;
    let mut v37: f32 = 0.0f32;
    let mut v38: i32 = 0i32;
    let mut v39: i32 = 0i32;
    let mut v40: i32 = 0i32;
    let mut v41: i32 = 0i32;
    let mut v42: i32 = 0i32;
    let mut v43: i32 = 0i32;
    let mut v44: i32 = 0i32;
    let mut v45: i32 = 0i32;
    let mut v46: i32 = 0i32;
    let mut v47: i32 = 0i32;
    let mut v48: i32 = 0i32;
    let mut v49: i32 = 0i32;
    let mut v50: i32 = 0i32;
    let mut v51: i32 = 0i32;
    let mut v52: i32 = 0i32;
    let mut v53: i32 = 0i32;
    let mut v54: i32 = 0i32;
    let mut v55: i32 = 0i32;
    let mut v56: i32 = 0i32;
    let mut v57: i32 = 0i32;
    let mut v58: i32 = 0i32;
    let mut v59: f32 = 0.0f32;
    let mut v60: f32 = 0.0f32;
    let mut v61: f32 = 0.0f32;
    let mut v62: f32 = 0.0f32;
    let mut v63: f32 = 0.0f32;
    let mut v64: f32 = 0.0f32;
    let mut v65: f32 = 0.0f32;
    let mut v66: i32 = 0i32;
    let mut v67: i32 = 0i32;
    let mut v68: i32 = 0i32;
    let mut v69: i32 = 0i32;
    let mut v70: i32 = 0i32;
    let mut v71: i32 = 0i32;
    let mut v72: i32 = 0i32;
    let mut v73: i32 = 0i32;
    let mut v74: i32 = 0i32;
    let mut v75: i32 = 0i32;
    let mut v76: i32 = 0i32;
    let mut v77: i32 = 0i32;
    let mut v78: i32 = 0i32;
    let mut v79: i32 = 0i32;
    let mut v80: i32 = 0i32;
    let mut v81: i32 = 0i32;
    let mut v82: i32 = 0i32;
    let mut v83: i32 = 0i32;
    let mut v84: i32 = 0i32;
    let mut v85: i32 = 0i32;
    let mut v86: i32 = 0i32;
    let mut v87: i32 = 0i32;
    let mut v88: i32 = 0i32;
    let mut v89: i32 = 0i32;
    let mut v90: i32 = 0i32;
    let mut v91: i32 = 0i32;
    let mut v92: i32 = 0i32;
    let mut v93: f32 = 0.0f32;
    let mut v94: f32 = 0.0f32;
    let mut v95: i32 = 0i32;
    let mut v96: i32 = 0i32;
    let mut v97: i32 = 0i32;
    let mut v98: i32 = 0i32;
    let mut v99: i32 = 0i32;
    let mut v100: i32 = 0i32;
    let mut v101: i32 = 0i32;
    let mut v102: i32 = 0i32;
    let mut v103: f32 = 0.0f32;
    let mut v104: i32 = 0i32;
    let mut v105: i32 = 0i32;
    let mut v106: i32 = 0i32;
    let mut v107: i32 = 0i32;
    let mut v108: f32 = 0.0f32;
    let mut v109: f32 = 0.0f32;
    let mut v110: i32 = 0i32;
    let mut v111: i32 = 0i32;
    let mut v112: i32 = 0i32;
    let mut v113: i32 = 0i32;
    let mut v114: i32 = 0i32;
    let mut v115: f32 = 0.0f32;
    let mut v116: i32 = 0i32;
    let mut v117: f32 = 0.0f32;
    let mut v118: i32 = 0i32;
    let mut v119: f32 = 0.0f32;
    let mut v120: i32 = 0i32;
    let mut v121: i32 = 0i32;
    let mut v122: i32 = 0i32;
    let mut v123: f32 = 0.0f32;
    let mut v124: f32 = 0.0f32;
    let mut v125: i32 = 0i32;
    let mut v126: i32 = 0i32;
    let mut v127: i32 = 0i32;
    let mut v128: i32 = 0i32;
    let mut v129: i32 = 0i32;
    let mut v130: i32 = 0i32;
    let mut v131: i32 = 0i32;
    let mut v132: i32 = 0i32;
    let mut v133: i32 = 0i32;
    let mut v134: i32 = 0i32;
    let mut v135: i32 = 0i32;
    let mut v136: i32 = 0i32;
    let mut v137: i32 = 0i32;
    let mut v138: i32 = 0i32;
    let mut v139: i32 = 0i32;
    let mut v140: i32 = 0i32;
    let mut v141: i32 = 0i32;
    let mut v142: i32 = 0i32;
    let mut v143: f32 = 0.0f32;
    let mut v144: f32 = 0.0f32;
    let mut v145: f32 = 0.0f32;
    let mut v146: f32 = 0.0f32;
    let mut v147: f32 = 0.0f32;
    let mut v148: f32 = 0.0f32;
    let mut v149: f32 = 0.0f32;
    let mut v150: i32 = 0i32;
    let mut v151: i32 = 0i32;
    let mut v152: i32 = 0i32;
    let mut v153: i32 = 0i32;
    let mut v154: i32 = 0i32;
    let mut v155: i32 = 0i32;
    let mut v156: i32 = 0i32;
    let mut v157: i32 = 0i32;
    let mut v158: i32 = 0i32;
    let mut v159: i32 = 0i32;
    let mut v160: i32 = 0i32;
    let mut v161: i32 = 0i32;
    let mut v162: i32 = 0i32;
    let mut v163: i32 = 0i32;
    let mut v164: i32 = 0i32;
    let mut v165: i32 = 0i32;
    let mut v166: i32 = 0i32;
    let mut v167: i32 = 0i32;
    let mut v168: i32 = 0i32;
    let mut v169: f32 = 0.0f32;
    let mut v170: f32 = 0.0f32;
    let mut v171: f32 = 0.0f32;
    let mut v172: f32 = 0.0f32;
    let mut v173: f32 = 0.0f32;
    let mut v174: f32 = 0.0f32;
    let mut v175: f32 = 0.0f32;
    let mut v176: i32 = 0i32;
    let mut v177: i32 = 0i32;
    let mut v178: i32 = 0i32;
    let mut v179: i32 = 0i32;
    let mut v180: i32 = 0i32;
    let mut v181: i32 = 0i32;
    let mut v182: f32 = 0.0f32;
    let mut v183: f32 = 0.0f32;
    let mut v184: f32 = 0.0f32;
    let mut v185: f32 = 0.0f32;
    let mut v186: i32 = 0i32;
    let mut v187: i32 = 0i32;
    let mut v188: i32 = 0i32;
    let mut v189: f32 = 0.0f32;
    let mut v190: f32 = 0.0f32;
    let mut v191: f32 = 0.0f32;
    let mut v192: f32 = 0.0f32;
    let mut v193: f32 = 0.0f32;
    let mut v194: f32 = 0.0f32;
    let mut v195: i32 = 0i32;
    let mut v196: i32 = 0i32;
    let mut v197: i32 = 0i32;
    let mut v198: i32 = 0i32;
    let mut v199: i32 = 0i32;
    let mut v200: i32 = 0i32;
    let mut v201: i32 = 0i32;
    let mut v202: i32 = 0i32;
    let mut v203: i32 = 0i32;
    let mut v204: i32 = 0i32;
    let mut v205: i32 = 0i32;
    let mut v206: i32 = 0i32;
    let mut v207: i32 = 0i32;
    let mut v208: i32 = 0i32;
    let mut v209: i32 = 0i32;
    let mut v210: i32 = 0i32;
    let mut v211: i32 = 0i32;
    let mut v212: i32 = 0i32;
    let mut v213: i32 = 0i32;
    let mut v214: i32 = 0i32;
    let mut v215: i32 = 0i32;
    let mut v216: i32 = 0i32;
    let mut v217: i32 = 0i32;
    let mut v218: i32 = 0i32;
    let mut v219: i32 = 0i32;
    let mut v220: i32 = 0i32;
    let mut v221: i32 = 0i32;
    let mut v222: i32 = 0i32;
    let mut v223: i32 = 0i32;
    let mut v224: i32 = 0i32;
    let mut v225: i32 = 0i32;
    let mut v226: i32 = 0i32;
    let mut v227: i32 = 0i32;
    let mut v228: i32 = 0i32;
    let mut v229: i32 = 0i32;
    let mut v230: i32 = 0i32;
    let mut v231: i32 = 0i32;
    let mut v232: i32 = 0i32;
    let mut v233: i32 = 0i32;
    let mut v234: i32 = 0i32;
    let mut v235: i32 = 0i32;
    let mut v236: i32 = 0i32;
    let mut v237: i32 = 0i32;
    let mut v238: i32 = 0i32;
    let mut v239: i32 = 0i32;
    let mut v240: f32 = 0.0f32;
    let mut v241: f32 = 0.0f32;
    let mut v242: f32 = 0.0f32;
    let mut v243: f32 = 0.0f32;
    let mut v244: f32 = 0.0f32;
    let mut v245: f32 = 0.0f32;
    let mut v246: f32 = 0.0f32;
    let mut v247: i32 = 0i32;
    let mut v248: i32 = 0i32;
    let mut v249: i32 = 0i32;
    let mut v250: i32 = 0i32;
    let mut v251: i32 = 0i32;
    let mut v252: i32 = 0i32;
    let mut v253: i32 = 0i32;
    let mut v254: i32 = 0i32;
    let mut v255: i32 = 0i32;
    let mut v256: i32 = 0i32;
    let mut v257: i32 = 0i32;
    let mut v258: i32 = 0i32;
    let mut v259: i32 = 0i32;
    let mut v260: i32 = 0i32;
    let mut v261: i32 = 0i32;
    let mut v262: i32 = 0i32;
    let mut v263: i32 = 0i32;
    let mut v264: i32 = 0i32;
    let mut v265: i32 = 0i32;
    let mut v266: f32 = 0.0f32;
    let mut v267: f32 = 0.0f32;
    let mut v268: f32 = 0.0f32;
    let mut v269: f32 = 0.0f32;
    let mut v270: f32 = 0.0f32;
    let mut v271: f32 = 0.0f32;
    let mut v272: f32 = 0.0f32;
    let mut v273: i32 = 0i32;
    let mut v274: i32 = 0i32;
    let mut v275: i32 = 0i32;
    let mut v276: i32 = 0i32;
    let mut v277: i32 = 0i32;
    let mut v278: i32 = 0i32;
    let mut v279: i32 = 0i32;
    let mut v280: i32 = 0i32;
    let mut v281: i32 = 0i32;
    let mut v282: i32 = 0i32;
    let mut v283: i32 = 0i32;
    let mut v284: i32 = 0i32;
    let mut v285: i32 = 0i32;
    let mut v286: i32 = 0i32;
    let mut v287: i32 = 0i32;
    let mut v288: i32 = 0i32;
    let mut v289: i32 = 0i32;
    let mut v290: i32 = 0i32;
    let mut v291: i32 = 0i32;
    let mut v292: i32 = 0i32;
    let mut v293: i32 = 0i32;
    let mut v294: i32 = 0i32;
    let mut v295: i32 = 0i32;
    let mut v296: f32 = 0.0f32;
    let mut v297: f32 = 0.0f32;
    let mut v298: i32 = 0i32;
    let mut v299: i32 = 0i32;
    let mut v300: i32 = 0i32;
    let mut v301: f32 = 0.0f32;
    let mut v302: f32 = 0.0f32;
    let mut v303: i32 = 0i32;
    let mut v304: i32 = 0i32;
    let mut v305: i32 = 0i32;
    let mut v306: i32 = 0i32;
    let mut v307: i32 = 0i32;
    let mut v308: i32 = 0i32;
    let mut v309: i32 = 0i32;
    let mut v310: f32 = 0.0f32;
    let mut v311: f32 = 0.0f32;
    let mut v312: f32 = 0.0f32;
    let mut v313: i32 = 0i32;
    let mut v314: i32 = 0i32;
    let mut v315: i32 = 0i32;
    let mut v316: f32 = 0.0f32;
    let mut v317: f32 = 0.0f32;
    let mut v318: i32 = 0i32;
    let mut v319: f32 = 0.0f32;
    let mut v320: f32 = 0.0f32;
    let mut v321: f32 = 0.0f32;
    let mut v322: f32 = 0.0f32;
    let mut v323: f32 = 0.0f32;
    let mut v324: f32 = 0.0f32;
    let mut v325: i32 = 0i32;
    let mut v326: i32 = 0i32;
    let mut v327: f32 = 0.0f32;
    let mut v328: f32 = 0.0f32;
    let mut v329: f32 = 0.0f32;
    let mut v330: f32 = 0.0f32;
    let mut v331: f32 = 0.0f32;
    let mut v332: f32 = 0.0f32;
    let mut v333: f32 = 0.0f32;
    let mut v334: f32 = 0.0f32;
    let mut v335: f32 = 0.0f32;
    let mut v336: f32 = 0.0f32;
    let mut v337: f32 = 0.0f32;
    let mut v338: i32 = 0i32;
    let mut v339: f32 = 0.0f32;
    let mut v340: f32 = 0.0f32;
    let mut v341: f32 = 0.0f32;
    let mut v342: i32 = 0i32;
    let mut v343: f32 = 0.0f32;
    let mut v344: f32 = 0.0f32;
    let mut v345: f32 = 0.0f32;
    let mut v346: i32 = 0i32;
    let mut v347: i32 = 0i32;
    let mut v348: i32 = 0i32;
    let mut v349: i32 = 0i32;
    let mut v350: i32 = 0i32;
    let mut v351: i32 = 0i32;
    let mut v352: i32 = 0i32;
    let mut v353: i32 = 0i32;
    let mut v354: i32 = 0i32;
    let mut v355: i32 = 0i32;
    let mut v356: i32 = 0i32;
    let mut v357: i32 = 0i32;
    #[derive(Clone, Copy)]
    #[allow(dead_code)]
    enum Block { B0, B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, B15, B16, B17, B18, B19, B20, B21, B22, B23, B24, B25, B26, B27, B28, B29, B30, B31, B32, B33, B34, B35, B36, B37, B38, B39, B40, B41, B42, B43 }
    let mut __current_block = Block::B0;
    loop {
        match __current_block {
            Block::B0 => {
                v19 = v0;
                v20 = v1;
                v21 = v2;
                v22 = v3;
                v23 = v4;
                v24 = v5;
                v25 = v6;
                v26 = v7;
                v27 = v8;
                v28 = v9;
                v29 = v10;
                v30 = v11;
                v31 = v12;
                v32 = v13;
                v33 = v14;
                v34 = v15;
                v35 = v16;
                v36 = v17;
                v37 = v18;
                __current_block = Block::B1;
                continue;
            }
            Block::B1 => {
                v38 = v21;
                v39 = 4096i32;
                v40 = if v38 != v39 { 1i32 } else { 0i32 };
                if v40 != 0 {
                    __current_block = Block::B2;
                } else {
                    __current_block = Block::B13;
                }
                continue;
            }
            Block::B2 => {
                v41 = 0i32;
                v42 = v41;
                v43 = 12i32;
                v44 = v43;
                v45 = v21;
                v46 = v21;
                v47 = v46;
                v48 = v44;
                v50 = v42;
                __current_block = Block::B3;
                continue;
            }
            Block::B3 => {
                v49 = v21;
                v51 = v23;
                v52 = v24;
                v53 = v25;
                v54 = v26;
                v55 = v27;
                v56 = v28;
                v57 = v29;
                v58 = v30;
                v59 = v31;
                v60 = v32;
                v61 = v33;
                v62 = v34;
                v63 = v35;
                v64 = v36;
                v65 = v37;
                v66 = v48;
                if v66 != 0 {
                    __current_block = Block::B4;
                } else {
                    __current_block = Block::B6;
                }
                continue;
            }
            Block::B4 => {
                v67 = v47;
                v68 = 1i32;
                v69 = v67 & v68;
                v70 = v50;
                v71 = 1i32;
                v72 = v70.wrapping_shl((v71 & 31) as u32);
                v73 = v69 | v72;
                v74 = v73;
                v75 = v48;
                v76 = 1i32;
                v77 = v75.wrapping_sub(v76);
                v78 = v77;
                v79 = v47;
                v80 = 1i32;
                v81 = (v79 as u32).wrapping_shr((v80 & 31) as u32) as i32;
                v82 = v81;
                v47 = v82;
                v48 = v78;
                v50 = v74;
                __current_block = Block::B3;
                continue;
            }
            Block::B5 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B6 => {
                __current_block = Block::B7;
                continue;
            }
            Block::B7 => {
                __current_block = Block::B8;
                continue;
            }
            Block::B8 => {
                v83 = v49;
                v84 = v50;
                v85 = if v83 < v84 { 1i32 } else { 0i32 };
                if v85 != 0 {
                    __current_block = Block::B9;
                } else {
                    __current_block = Block::B10;
                }
                continue;
            }
            Block::B9 => {
                v86 = v49;
                v87 = 3i32;
                v88 = v86.wrapping_shl((v87 & 31) as u32);
                v89 = v88;
                v90 = 1024i32;
                v91 = v88.wrapping_add(v90);
                v92 = v91;
                v93 = memory.load_f32(v91 as usize)?;
                v94 = v93;
                v95 = v91;
                v96 = v50;
                v97 = 3i32;
                v98 = v96.wrapping_shl((v97 & 31) as u32);
                v99 = v98;
                v100 = 1024i32;
                v101 = v98.wrapping_add(v100);
                v102 = v101;
                v103 = memory.load_f32(v101 as usize)?;
                memory.store_f32(v95 as usize, v103)?;
                v104 = v88;
                v105 = 1028i32;
                v106 = v104.wrapping_add(v105);
                v107 = v106;
                v108 = memory.load_f32(v106 as usize)?;
                v109 = v108;
                v110 = v106;
                v111 = v98;
                v112 = 1028i32;
                v113 = v111.wrapping_add(v112);
                v114 = v113;
                v115 = memory.load_f32(v113 as usize)?;
                memory.store_f32(v110 as usize, v115)?;
                v116 = v101;
                v117 = v93;
                memory.store_f32(v116 as usize, v117)?;
                v118 = v113;
                v119 = v108;
                memory.store_f32(v118 as usize, v119)?;
                v120 = v114;
                v121 = v99;
                v122 = v102;
                v123 = v94;
                v124 = v109;
                __current_block = Block::B11;
                continue;
            }
            Block::B10 => {
                v120 = v47;
                v121 = v48;
                v122 = v50;
                v123 = v59;
                v124 = v60;
                __current_block = Block::B11;
                continue;
            }
            Block::B11 => {
                v125 = v49;
                v126 = 1i32;
                v127 = v125.wrapping_add(v126);
                v128 = v127;
                v19 = v120;
                v20 = v121;
                v21 = v128;
                v22 = v122;
                v23 = v51;
                v24 = v52;
                v25 = v53;
                v26 = v54;
                v27 = v55;
                v28 = v56;
                v29 = v57;
                v30 = v58;
                v31 = v123;
                v32 = v124;
                v33 = v61;
                v34 = v62;
                v35 = v63;
                v36 = v64;
                v37 = v65;
                __current_block = Block::B1;
                continue;
            }
            Block::B12 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B13 => {
                __current_block = Block::B14;
                continue;
            }
            Block::B14 => {
                __current_block = Block::B15;
                continue;
            }
            Block::B15 => {
                v129 = 2i32;
                v130 = v129;
                v131 = v19;
                v132 = v20;
                v133 = v130;
                v134 = v22;
                v135 = v23;
                v136 = v24;
                v137 = v25;
                v138 = v26;
                v139 = v27;
                v140 = v28;
                v141 = v29;
                v142 = v30;
                v143 = v31;
                v144 = v32;
                v145 = v33;
                v146 = v34;
                v147 = v35;
                v148 = v36;
                v149 = v37;
                __current_block = Block::B16;
                continue;
            }
            Block::B16 => {
                v150 = v133;
                v151 = 4097i32;
                v152 = if (v150 as u32) >= (v151 as u32) { 1 } else { 0 };
                if v152 != 0 {
                    __current_block = Block::B17;
                } else {
                    __current_block = Block::B23;
                }
                continue;
            }
            Block::B17 => {
                v153 = -8192i32;
                v154 = v153;
                v155 = 1024i32;
                v156 = v155;
                v157 = v156;
                v158 = v154;
                v169 = v143;
                __current_block = Block::B18;
                continue;
            }
            Block::B18 => {
                v159 = v133;
                v160 = v134;
                v161 = v135;
                v162 = v136;
                v163 = v137;
                v164 = v138;
                v165 = v139;
                v166 = v140;
                v167 = v141;
                v168 = v142;
                v170 = v144;
                v171 = v145;
                v172 = v146;
                v173 = v147;
                v174 = v148;
                v175 = v149;
                v176 = v158;
                v177 = if v176 == 0 { 1 } else { 0 };
                if v177 != 0 {
                    __current_block = Block::B38;
                } else {
                    __current_block = Block::B19;
                }
                continue;
            }
            Block::B19 => {
                v178 = v158;
                v179 = 41984i32;
                v180 = v178.wrapping_add(v179);
                v181 = v157;
                v182 = memory.load_f32(v181 as usize)?;
                v183 = v182;
                v184 = v182;
                v185 = v182 * v184;
                v186 = v157;
                v187 = 4i32;
                v188 = v186.wrapping_add(v187);
                v189 = memory.load_f32(v188 as usize)?;
                v190 = v189;
                v191 = v189;
                v192 = v189 * v191;
                v193 = v185 + v192;
                v194 = v193.sqrt();
                memory.store_f32(v180 as usize, v194)?;
                v195 = v157;
                v196 = 8i32;
                v197 = v195.wrapping_add(v196);
                v198 = v197;
                v199 = v158;
                v200 = 4i32;
                v201 = v199.wrapping_add(v200);
                v202 = v201;
                v157 = v198;
                v158 = v202;
                v169 = v190;
                __current_block = Block::B18;
                continue;
            }
            Block::B20 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B21 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B22 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B23 => {
                __current_block = Block::B24;
                continue;
            }
            Block::B24 => {
                v203 = v133;
                v204 = 3i32;
                v205 = v203.wrapping_shl((v204 & 31) as u32);
                v206 = v205;
                v207 = 1024i32;
                v208 = v207;
                v209 = v133;
                v210 = 2i32;
                v211 = v209.wrapping_shl((v210 & 31) as u32);
                v212 = v211;
                v213 = 1024i32;
                v214 = v211.wrapping_add(v213);
                v215 = v214;
                v216 = 2048i32;
                v217 = v133;
                v218 = 1i32;
                v219 = (v217 as u32).wrapping_shr((v218 & 31) as u32) as i32;
                v220 = 65535i32;
                v221 = v219 & v220;
                v222 = i32_div_u(v216, v221)?;
                v223 = 2i32;
                v224 = v222.wrapping_shl((v223 & 31) as u32);
                v225 = v224;
                v226 = 0i32;
                v227 = v226;
                v228 = v131;
                v229 = v132;
                v230 = v133;
                v231 = v208;
                v232 = v135;
                v233 = v215;
                v234 = v227;
                v235 = v206;
                v236 = v139;
                v237 = v212;
                v238 = v225;
                v239 = v142;
                v240 = v143;
                v241 = v144;
                v242 = v145;
                v243 = v146;
                v244 = v147;
                v245 = v148;
                v246 = v149;
                __current_block = Block::B25;
                continue;
            }
            Block::B25 => {
                v247 = v234;
                v248 = 4095i32;
                v249 = if (v247 as u32) > (v248 as u32) { 1 } else { 0 };
                if v249 != 0 {
                    __current_block = Block::B40;
                } else {
                    __current_block = Block::B26;
                }
                continue;
            }
            Block::B26 => {
                v250 = 0i32;
                v251 = v250;
                v252 = 0i32;
                v253 = v252;
                v254 = v251;
                v255 = v253;
                v258 = v232;
                v262 = v236;
                v265 = v239;
                v266 = v240;
                v267 = v241;
                v268 = v242;
                v269 = v243;
                v270 = v244;
                v271 = v245;
                v272 = v246;
                __current_block = Block::B27;
                continue;
            }
            Block::B27 => {
                v256 = v230;
                v257 = v231;
                v259 = v233;
                v260 = v234;
                v261 = v235;
                v263 = v237;
                v264 = v238;
                v273 = v255;
                v274 = v237;
                v275 = if v273 == v274 { 1i32 } else { 0i32 };
                if v275 != 0 {
                    __current_block = Block::B28;
                } else {
                    __current_block = Block::B30;
                }
                continue;
            }
            Block::B28 => {
                v276 = v259;
                v277 = v261;
                v278 = v276.wrapping_add(v277);
                v279 = v278;
                v280 = v257;
                v281 = v261;
                v282 = v280.wrapping_add(v281);
                v283 = v282;
                v284 = v256;
                v285 = v260;
                v286 = v284.wrapping_add(v285);
                v287 = v286;
                v228 = v254;
                v229 = v255;
                v230 = v256;
                v231 = v283;
                v232 = v258;
                v233 = v279;
                v234 = v287;
                v235 = v261;
                v236 = v262;
                v237 = v263;
                v238 = v264;
                v239 = v265;
                v240 = v266;
                v241 = v267;
                v242 = v268;
                v243 = v269;
                v244 = v270;
                v245 = v271;
                v246 = v272;
                __current_block = Block::B25;
                continue;
            }
            Block::B29 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B30 => {
                v288 = v255;
                v289 = v257;
                v290 = v288.wrapping_add(v289);
                v291 = v290;
                v292 = 4i32;
                v293 = v290.wrapping_add(v292);
                v294 = v293;
                v295 = v293;
                v296 = memory.load_f32(v295 as usize)?;
                v297 = v296;
                v298 = v254;
                v299 = 41984i32;
                v300 = v298.wrapping_add(v299);
                v301 = memory.load_f32(v300 as usize)?;
                v302 = v301;
                v303 = v255;
                v304 = v259;
                v305 = v303.wrapping_add(v304);
                v306 = v305;
                v307 = 4i32;
                v308 = v305.wrapping_add(v307);
                v309 = v308;
                v310 = memory.load_f32(v308 as usize)?;
                v311 = v310;
                v312 = v301 * v310;
                v313 = v254;
                v314 = 50176i32;
                v315 = v313.wrapping_add(v314);
                v316 = memory.load_f32(v315 as usize)?;
                v317 = v316;
                v318 = v305;
                v319 = memory.load_f32(v318 as usize)?;
                v320 = v319;
                v321 = v316 * v319;
                v322 = v312 + v321;
                v323 = v322;
                v324 = v296 + v322;
                memory.store_f32(v293 as usize, v324)?;
                v325 = v290;
                v326 = v290;
                v327 = memory.load_f32(v326 as usize)?;
                v328 = v327;
                v329 = v301;
                v330 = v319;
                v331 = v329 * v330;
                v332 = v310;
                v333 = v316;
                v334 = v332 * v333;
                v335 = v331 - v334;
                v336 = v335;
                v337 = v327 + v335;
                memory.store_f32(v325 as usize, v337)?;
                v338 = v305;
                v339 = v327;
                v340 = v335;
                v341 = v339 - v340;
                memory.store_f32(v338 as usize, v341)?;
                v342 = v308;
                v343 = v296;
                v344 = v322;
                v345 = v343 - v344;
                memory.store_f32(v342 as usize, v345)?;
                v346 = v254;
                v347 = v264;
                v348 = v346.wrapping_add(v347);
                v349 = v348;
                v350 = v255;
                v351 = 8i32;
                v352 = v350.wrapping_add(v351);
                v353 = v352;
                v254 = v349;
                v255 = v353;
                v258 = v306;
                v262 = v291;
                v265 = v309;
                v266 = v297;
                v267 = v336;
                v268 = v311;
                v269 = v317;
                v270 = v320;
                v271 = v323;
                v272 = v328;
                __current_block = Block::B27;
                continue;
            }
            Block::B31 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B32 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B33 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B34 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B35 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B36 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B37 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B38 => {
                return Ok(());
            }
            Block::B39 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B40 => {
                v354 = v230;
                v355 = 1i32;
                v356 = v354.wrapping_shl((v355 & 31) as u32);
                v357 = v356;
                v131 = v228;
                v132 = v229;
                v133 = v357;
                v134 = v231;
                v135 = v232;
                v136 = v233;
                v137 = v234;
                v138 = v235;
                v139 = v236;
                v140 = v237;
                v141 = v238;
                v142 = v239;
                v143 = v240;
                v144 = v241;
                v145 = v242;
                v146 = v243;
                v147 = v244;
                v148 = v245;
                v149 = v246;
                __current_block = Block::B16;
                continue;
            }
            Block::B41 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B42 => {
    return Err(WasmTrap::Unreachable);
            }
            Block::B43 => {
                return Ok(());
            }
        }
    }
}

#[allow(unused_mut, unused_variables, unused_assignments, clippy::only_used_in_recursion, clippy::needless_return, clippy::manual_range_contains, clippy::never_loop)]
fn func_4<H: ModuleHostTrait>(env: &mut Env<'_, H>, memory: &mut IsolatedMemory<MAX_PAGES>) -> WasmResult<i32> {
    let mut v1: i32 = 0i32;
    #[derive(Clone, Copy)]
    #[allow(dead_code)]
    enum Block { B0 }
    let mut __current_block = Block::B0;
    loop {
        match __current_block {
            Block::B0 => {
                v1 = 33792i32;
                return Ok(v1);
            }
        }
    }
}

impl WasmModule {
    pub fn __wasm_call_ctors(&mut self) -> WasmResult<()> {
        let mut __host = herkos_runtime::NoHost;
        let mut env = Env { host: &mut __host, globals: &mut self.0.globals };
        func_0(&mut env, &mut self.0.memory)
    }
    pub fn fft_init(&mut self, v0: i32) -> WasmResult<()> {
        let mut __host = herkos_runtime::NoHost;
        let mut env = Env { host: &mut __host, globals: &mut self.0.globals };
        func_1(v0, &mut env, &mut self.0.memory)
    }
    pub fn fft_get_input_ptr(&mut self) -> WasmResult<i32> {
        let mut __host = herkos_runtime::NoHost;
        let mut env = Env { host: &mut __host, globals: &mut self.0.globals };
        func_2(&mut env, &mut self.0.memory)
    }
    pub fn fft_compute(&mut self, v0: i32) -> WasmResult<()> {
        let mut __host = herkos_runtime::NoHost;
        let mut env = Env { host: &mut __host, globals: &mut self.0.globals };
        func_3(v0, &mut env, &mut self.0.memory)
    }
    pub fn fft_get_output_ptr(&mut self) -> WasmResult<i32> {
        let mut __host = herkos_runtime::NoHost;
        let mut env = Env { host: &mut __host, globals: &mut self.0.globals };
        func_4(&mut env, &mut self.0.memory)
    }
}

